a=int(input('Enter 1st number: '))
b=int(input('Enter 2nd number: '))
c=int(input('Enter 3rd number: '))
d=int(input('Enter 4th number: '))
e=int(input('Enter 5th number: '))
print('The Average Of 5 Numbers Is: ',(a+b+c+d+e)/5)
